struct CommonUniforms {
	mat4  model;
	vec4  color;
	int   use_pbr;
	float roughness;
	float metallic;
	float ao;
	int   use_texture;
	int   is_line;
	int   line_style;
	int   is_text_effect;
	float text_fade_progress;
	float text_fade_softness;
	int   text_fade_mode;
	int   is_arcade_text;
	int   arcade_wave_mode;
	float arcade_wave_amplitude;
	float arcade_wave_frequency;
	float arcade_wave_speed;
	int   arcade_rainbow_enabled;
	float arcade_rainbow_speed;
	float arcade_rainbow_frequency;
	int   checkpoint_style;
	int   is_colossal;
	int   use_ssbo_instancing;
	int   use_vertex_color;
	float checkpoint_radius;
};
