#version 430 core

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding = 0) uniform sampler3D u_src_3d;
layout(rgba32f, binding = 0) uniform writeonly image2D u_dst_2d;

uniform float u_z_slice; // 0.0 to 1.0

void main() {
	ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(u_dst_2d);
	if (pos.x >= size.x || pos.y >= size.y) return;

	vec2 uv = vec2(pos) / vec2(size - 1);
	vec3 uvw = vec3(uv, u_z_slice);
	vec4 col = texture(u_src_3d, uvw);

	imageStore(u_dst_2d, pos, col);
}
