#version 430 core

layout(local_size_x = 256) in;

layout(std430, binding = 0) buffer Data {
    uint u_data[];
};

layout(std430, binding = 1) readonly buffer BlockSums {
    uint u_blockSums[];
};

uniform uint u_numElements;

void main() {
    uint gid = gl_GlobalInvocationID.x;
    if (2 * gid >= u_numElements) return;

    uint blockSum = u_blockSums[gl_WorkGroupID.x];

    u_data[2 * gid] += blockSum;
    if (2 * gid + 1 < u_numElements) {
        u_data[2 * gid + 1] += blockSum;
    }
}
