#version 460 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba32f) uniform image2D outJFA;
uniform sampler2D uInputJFA;
uniform float uJumpStep;

#define JUMPFLOOD_TYPE vec4
#include "lygia/morphological/jumpFlood.glsl"

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outJFA);
    if (pixel.x >= size.x || pixel.y >= size.y) return;

    vec2 uv = (vec2(pixel) + 0.5) / vec2(size);
    vec2 pixelSize = 1.0 / vec2(size);

    vec4 data = jumpFloodIterate(uInputJFA, uv, pixelSize, uJumpStep);

    imageStore(outJFA, pixel, data);
}
