#version 460 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba16f) uniform image2D outWeatherMap;

#include "../helpers/fast_noise.glsl"

uniform float uWorldScale;
uniform float uCloudCoverage;


// Tiling 3D Worley/Cellular noise
vec3 cloudMapGen(vec3 p, float period) {
	vec3  i = floor(p);
	vec3  f = fract(p);
	float  f1 = 1e6;
	float  f2 = 1e6;
	vec3 cellId = vec3(0);
	for (int z = -1; z <= 1; z++) {
		for (int y = -1; y <= 1; y++) {
			for (int x = -1; x <= 1; x++) {
				vec3 neighbor = vec3(float(x), float(y), float(z));
				// Wrap neighbor + i to [0, period-1]
				vec3 wrapped_coord = mod(i + neighbor, period);
				vec3 point = hash33(wrapped_coord);
				vec3 diff = neighbor + point - f;
				float d = dot(diff, diff);
				if (d < f1) {
					f2 = f1;
					f1 = d;
					// cellId = random(point); // Use the x component of the cell's random point as the ID
					// cellId = (simplex3d_tiling(point, period)+1.0)*0.5; // Use the x component of the cell's random point as the ID
					cellId = point;
				}
				else if (d < f2) {
					f2 = d;
				}
			}
		}
	}
	return vec3(sqrt(f1), sqrt(f2), (simplex3d_tiling(cellId, period)+1.0)*0.5);
}

// Tiling 3D FBM Perlin (using pnoise for classic Perlin)
float simplexTiledWithGrad(vec3 p, float period) {
	vec3 gradient;
	float value = 0.0;
	float amplitude = 0.5;
	for (int i = 0; i < 4; i++) {
        vec3 g;
		value += amplitude * psrdnoise(p, vec3(period), 0.0, g);
		p *= 2.0;
		period *= 2.0;
        gradient += amplitude * g;
		amplitude *= 0.5;
	}
	return value;
}


void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outWeatherMap);
    if (pixel.x >= size.x || pixel.y >= size.y) return;

    vec2 uv = (vec2(pixel) + 0.5) / vec2(size);

    // We bake a "canonical" weather map that is static in local space.
    // Raymarching will apply wind advection as an offset to the sampling UV.
    // To make it "non-obvious" when it wraps, it should be large.
    // 2048 texture at 10000 scale means one tile is 20,480,000 units.

    vec3 p = vec3(uv.x * 100000.0 * uWorldScale, 0.0, uv.y * 100000.0 * uWorldScale);

	vec3 wibby = vec3(0.0);//(simplex3d_tiling(p, 16)+1.0)*0.5 * 0.005*length(p)*computeCurl(p, 16);
	wibby.y = 0.0;

    vec3 weatherData = cloudMapGen((p + wibby)/ (10000.0 * uWorldScale), 16.0);
    // float weatherData = fbm3d_tiling(p/10000, 32);
    // float weatherMap = step(1.0 - uCloudCoverage, abs(1-weatherData.x));
    // float weatherMap = (weatherData+1)*0.5;
    // float weatherMap = uCloudCoverage * abs(weatherData.y);
    float weatherMap = uCloudCoverage * weatherData.y-weatherData.x;
    float cellID = weatherData.z;
    // float cellID = 7;

    // Height/Altitude needs its own frequency
    // Use ID variant to get both a gradual distance (G) and a per-cell variety ID (A)
    vec2 heightData = worley3d_tiling(p / (20000.0 * uWorldScale), 16.0);
    float altitudeMap = abs(1.0 - heightData.x);
    float thicknessMap = heightData.y;

    imageStore(outWeatherMap, pixel, vec4(weatherMap, altitudeMap, cellID, thicknessMap));
}
