#version 460 core

layout(local_size_x = 8, local_size_y = 4, local_size_z = 8) in;

layout(binding = 0, r32f) uniform image3D outSdfTexture;

#include "../helpers/clouds.glsl"

void main() {
	ivec3 pixel = ivec3(gl_GlobalInvocationID.xyz);
	ivec3 size = imageSize(outSdfTexture); // 128x32x128
	if (pixel.x >= size.x || pixel.y >= size.y || pixel.z >= size.z) return;

	vec3 texCoords = (vec3(pixel) + 0.5) / vec3(size);

	// Setup cloud properties from the global Lighting block
	CloudProperties props;
	props.altitude = cloudAltitude;
	props.thickness = cloudThickness;
	props.densityBase = cloudDensity;
	props.coverage = cloudCoverage;
	props.worldScale = worldScale;

	// X and Z coordinates represent 1 full period of uv space: p_advected / (1000.0 * props.worldScale)
	float mapRange = 6000.0 * props.worldScale;
	float worldX = texCoords.x * mapRange;
	float worldZ = texCoords.z * mapRange;

	// Y coordinate represents the altitude range of the cloud layer
	float y_min = props.altitude * props.worldScale;
	float y_max = (props.altitude + props.thickness * 12.0) * props.worldScale;
	float worldY = y_min + texCoords.y * (y_max - y_min);

	vec3 p = vec3(worldX, worldY, worldZ);
	vec3 voxelSize = vec3(
		mapRange / float(size.x),
		(y_max - y_min) / float(size.y),
		mapRange / float(size.z)
	);

// The distance from the center of the voxel to its furthest corner
	float voxelCircumradius = length(voxelSize) * 0.5;


	float d3d = evalSdf(p, time, props);

	// Dilate the SDF to ensure the bounding box covers voxel corners
	d3d -= voxelCircumradius;
	// p.xz /= 6.0;

	imageStore(outSdfTexture, pixel, vec4(d3d, 0.0, 0.0, 0.0));
}
