#version 460 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

layout(binding = 0, rgba16f) uniform image3D outVolume;

void main() {
	ivec3 voxel = ivec3(gl_GlobalInvocationID.xyz);
	ivec3 size = imageSize(outVolume); // 128, 128, 128
	if (voxel.x >= size.x || voxel.y >= size.y || voxel.z >= size.z) return;
	vec3 voxelSize = vec3(100000.0, 700, 100000.0) / 128.0;
	// Evaluate the local density environment
	float densitySum = 0.0;
	const int AO_SAMPLES = 8;
	vec3 physical_ao_offsets[AO_SAMPLES] = vec3[](
		vec3(0.0, 200.0, 0.0),
		vec3(0.0, 500.0, 0.0),
		vec3(0.0, 1000.0, 0.0),
		vec3(300.0, 400.0, 300.0),
		vec3(-300.0, 400.0, -300.0),
		vec3(400.0, 800.0, -400.0),
		vec3(-400.0, 800.0, 400.0),
		vec3(0.0, 1500.0, 0.0)
	);

	for (int i = 0; i < AO_SAMPLES; i++) {
		vec3 voxelOffset = physical_ao_offsets[i] / voxelSize;
		ivec3 sample_voxel = ivec3(floor(vec3(voxel) + voxelOffset));

		float sampleDensity = imageLoad(outVolume, sample_voxel).a;
		densitySum += sampleDensity;
	}
	float aoVal = clamp(1.0 - (densitySum / float(AO_SAMPLES)) * 1.5, 0.0, 1.0);

	vec4 currentVal = imageLoad(outVolume, voxel);
	currentVal.g = aoVal;
	imageStore(outVolume, voxel, currentVal);
}
