import json
import re

def parse_wordnet_to_engine_format(synset_file, word_file, output_terminals, output_triples):
    print("Loading JSON files...")
    with open(synset_file, 'r', encoding='utf-8') as f:
        synsets = json.load(f)
    with open(word_file, 'r', encoding='utf-8') as f:
        words = json.load(f)

    # WordNet POS to Grammar POS mapping
    pos_map = {
        'n': 'N',
        'v': 'V',     # Note: WordNet doesn't split Transitive/Intransitive
        'a': 'ADJ',
        's': 'ADJ',   # Satellite adjective
        'r': 'ADV'
    }

    # Data structures for processing
    synset_members = {}
    sense_id_to_word = {}
    lexicon = set()
    triples = set()

    print("Pass 1: Processing Synsets (Synonyms and Structural Links)...")
    for syn_id, data in synsets.items():
        # Skip root-level metadata keys that aren't dictionaries
        if not isinstance(data, dict):
            continue

        raw_members = data.get('members', [])
        if isinstance(raw_members, str):
            raw_members = [raw_members]

        # Clean words, ensuring we only call replace() on actual strings
        members = [w.replace(' ', '_').lower() for w in raw_members if isinstance(w, str)]
        synset_members[syn_id] = members

        # 1. Intra-synset relations
        for i in range(len(members)):
            for j in range(i + 1, len(members)):
                triples.add((members[i], 'synonym', members[j]))
                triples.add((members[j], 'synonym', members[i]))

    # Extract Inter-Synset relations (e.g., 'similar', 'hypernym')
    # Feel free to add more relation strings to this list based on your JSON schema
    relation_keys = ['similar', 'hypernym', 'hyponym', 'also']
    for syn_id, data in synsets.items():
        source_words = synset_members.get(syn_id, [])
        for rel_key in relation_keys:
            if rel_key in data:
                # Some WordNet formats make this a list, some a string
                targets = data[rel_key] if isinstance(data[rel_key], list) else [data[rel_key]]
                for target_id in targets:
                    target_words = synset_members.get(target_id, [])
                    # Link every word in the source synset to every word in the target synset
                    for sw in source_words:
                        for tw in target_words:
                            triples.add((sw, rel_key, tw))

    print("Pass 2: Processing Lexicon (POS extraction and Sense Links)...")
    for word, pos_data in words.items():
        if not isinstance(pos_data, dict):
            continue

        clean_word = str(word).replace(' ', '_').lower()

        for pos, details in pos_data.items():
            if not isinstance(details, dict):
                continue

            # 1. Output the Grammar Terminal
            if pos in pos_map:
                lexicon.add(f"1.0 {pos_map[pos]} {clean_word}")

            # 2. Map Sense IDs for Antonym lookups
            for sense in details.get('sense', []):
                if isinstance(sense, dict):
                    sense_id = sense.get('id')
                    if sense_id:
                        sense_id_to_word[sense_id] = clean_word

    print("Pass 3: Resolving Sense-level relations (Antonyms)...")
    for word, pos_data in words.items():
        if not isinstance(pos_data, dict):
            continue

        clean_source_word = str(word).replace(' ', '_').lower()
        for pos, details in pos_data.items():
            if not isinstance(details, dict):
                continue

            for sense in details.get('sense', []):
                if isinstance(sense, dict) and 'antonym' in sense:
                    for ant_id in sense['antonym']:
                        target_word = sense_id_to_word.get(ant_id)

                        if not target_word:
                            target_word = str(ant_id).split('%')[0].replace(' ', '_')

                        triples.add((clean_source_word, 'antonym', target_word))
                        triples.add((target_word, 'antonym', clean_source_word))

    print("Writing output files...")
    # Write Grammar Terminals
    with open(output_terminals, 'w', encoding='utf-8') as f:
        f.write("# --- AUTOGENERATED WORDNET TERMINALS ---\n")
        # Sort alphabetically by POS tag, then by word
        for line in sorted(list(lexicon), key=lambda x: (x.split()[1], x.split()[2])):
            f.write(f"{line}\n")

    # Write Semantic Triples
    with open(output_triples, 'w', encoding='utf-8') as f:
        # Sort alphabetically by subject
        for sub, rel, obj in sorted(list(triples)):
            f.write(f"{sub} {rel} {obj}\n")

    print(f"Done! Extracted {len(lexicon)} terminals and {len(triples)} relationship triples.")

# --- Execution ---
if __name__ == "__main__":
    # Replace these filenames with your actual local file paths
    SYNSET_FILE = "megaSynset.json"
    WORD_FILE = "megaEntry.json"

    TERMINALS_OUT = "grammar_terminals.txt"
    TRIPLES_OUT = "semantic_triples.txt"

    parse_wordnet_to_engine_format(SYNSET_FILE, WORD_FILE, TERMINALS_OUT, TRIPLES_OUT)